# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

courses = []
choice = 'random'

def line():
    print('---------------------------------------------')

def show_menu():
    line()
    print('Options')
    line()
    print('1. Add new course')
    print('2. Remove a course')
    print('3. View all courses')
    print('4. Exit')
    line()
    choice = input('Enter your choice: ')
    return choice

while choice!= '4':
    choice = show_menu()
    if choice == '1':
        item = input('Course Name: ')
        courses.append(item)
        print('Course ',item,' added')
    elif choice =='2':
        item = input('Which course do you want to remove or unroll? ')
        if item in courses:
            courses.remove(item)
            print('Unrolled from ',item,' course')
        else:
            print('You are not enrolled in this course')
    elif choice == '3':
        print('List of all enrolled courses:')
        for item in courses:
            print(item)
    elif choice == '4':
        print('Bye')
    else:
        print('Please enter one of 1,2,3 or 4')